export const vinhos = [
    {
        nome: 'Rosé da Serra',
        preco: 'R$ 49,90',
        tipo: 'rose',
        descricao: 'Vinho rosé leve e refrescante, com notas de frutas vermelhas.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=515,q=99/assets-images/produtos/31847-01.png',
        teorAlcool: '12%',
    },
    {
        nome: 'Tinto Vale Dourado',
        preco: 'R$ 59,90',
        tipo: 'tinto',
        descricao: 'Vinho tinto encorpado, com aromas de frutas maduras e especiarias.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/31067-01.png',
        teorAlcool: '13,5%',
    },
    {
        nome: 'Branco Brisa do Vale',
        preco: 'R$ 44,90',
        tipo: 'branco',
        descricao: 'Vinho branco fresco e aromático, com notas cítricas e florais.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/32366-01.png',
        teorAlcool: '11,5%',
    },
    {
        nome: 'Rosé Pétalas do Sol',
        preco: 'R$ 52,90',
        tipo: 'rose',
        descricao: 'Rosé elegante com toques de morango, pêssego e final suave.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/26160-01.png',
        teorAlcool: '12,5%',
    },
    {
        nome: 'Rosé Primavera',
        preco: 'R$ 39,90',
        tipo: 'rose',
        descricao: 'Vinho jovem e vibrante, ideal para dias quentes e pratos leves.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/30796-01.png',
        teorAlcool: '11,8%',
    },
    {
        nome: 'Tinto Reserva da Magueira',
        preco: 'R$ 89,90',
        tipo: 'tinto',  
        descricao: 'Tinto nobre estagiado em carvalho, com notas de baunilha e cacau.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/31640-01.png',
        teorAlcool: '14%',
    },
    {
        nome: 'Tinto Cordilheira',
        preco: 'R$ 64,90',
        tipo: 'tinto',
        descricao: 'Vinho equilibrado com taninos macios e aroma marcante de ameixa.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/31982-01.png',
        teorAlcool: '13,8%',
    },
    {
        nome: 'Branco Sol de Verão',
        preco: 'R$ 47,90',
        tipo: 'branco',
        descricao: 'Branco mineral e crocante, excelente para acompanhar frutos do mar.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/32248-01.png',
        teorAlcool: '12%',
    },
    {
        nome: 'Branco Quinta dos Pomares',
        preco: 'R$ 54,90',
        tipo: 'branco',
        descricao: 'Vinho com destaque para acidez equilibrada e notas marcantes de maçã verde.',
        imagem: 'https://www.wine.com.br/cdn-cgi/image/f=png,h=176,q=99/assets-images/produtos/32094-01.png',
        teorAlcool: '12,2%',
    }
];